### ISSUE TITLE
Which Licence?

### ISSUE THREAD

**Issue by henryoswald** [coreh-deprecated/nide#1]
Fantastically sleek implementation. Very impressive. 
There isn't a clear licence with it yet, are their any plans?

**Comment by psugihara** [comment]
Check the features sections here: http://coreh.github.com/nide/

"Nide is distributed under the MIT license." !!! :)

**Comment by henryoswald** [comment]
great thanks, interesting stuff.

**Comment by coreh** [comment]
Hey @henryoswald, thanks! :-)

As @ptrsghr said, it's MIT licensed. I forgot to add a LICENSE file. I'll drop it soon on the repository.
