### ISSUE TITLE
Could you update the package.json to allow install in node 0.6.x?

### ISSUE THREAD

**Issue by baggachipz** [coreh-deprecated/nide#16]
Looks like the package.json is out of date; I could of course fork with that but I'm not sure if there are any dependencies or limitations that I'm not aware of.

**Comment by coreh** [comment]
Hey @baggachipz,

I had to bump some of the dependencies that were listed to get it working under 0.6.x, but now it seems to be working just fine. 

I've released a new version, v0.1.5, with the updated `package.json`. Tell me if it works OK. I'm marking this issue as fixed for now.

**Comment by baggachipz** [comment]
Great, thanks! Love Nide.
