### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by Nexum** [coreh-deprecated/nide#18]
I would really like to see a simple .htaccess style Authentification so not everyone can use the editor, i could really use this when developing on a foreign machine :)

**Comment by coreh** [comment]
You're right, that's useful for remote access. I'll add a command line argument that triggers connect's `basicAuth` middleware. 

How important do you think it is to be able to specify the password via a config file? For your use case, is it enough to pass it directly from the command line? Something like:

```
$ nide --username AzureDiamond --password hunter2
```

**Comment by Nexum** [comment]
Hm i think that would be enough for a start, better would be to specify a file where we could set a user and password. i would like to try to implement nide into a cms, something like "activate nide" then get an overlay with nide inside an iframe, now this should be password protected so i can send this information when opening the iframe and no one could intercept, but everyone in my application could use it :)

**Comment by Nexum** [comment]
When i think about it, command line would really be enough, i can then configure a node script with the username and password and start nide from inside of the script.

**Comment by coreh** [comment]
The latest version on the repository now supports this. I'm going to include it on the next release.
