### ISSUE TITLE
Specify host IP

### ISSUE THREAD

**Issue by iwizardpro** [coreh-deprecated/nide#22]
Hello,

Is there a way to specifically bind to an IP for Nide? I don't want the production stuff to be accessible by the public.

Thanks!

**Comment by coreh** [comment]
The latest version in the repository now supports this. I'm going to include it on the next release. Can you test it and see if it works and suits your needs?

**Comment by iwizardpro** [comment]
Yeah, I just tested it and it works perfectly.

**Comment by coreh** [comment]
:-) Marking this as closed then.
