### ISSUE TITLE
Force refresh of project tree view

### ISSUE THREAD

**Issue by cmundi** [coreh-deprecated/nide#30]
Currently, if the filesystem changes (e.g. mkdir a new directory from a console/xterm) nide seems not to notice until the next start.  Obviously, it would be great if nide could receive an event on changes anywhere under the working directory.  But just having a "refresh" button in nide would be great!

**Comment by iwizardpro** [comment]
I have a working modification for this. I will add a pull request for this shortly.

**Comment by cmundi** [comment]
Awesome!
On Dec 29, 2011 9:38 PM, "Ryan Tse" <
reply@reply.github.com>
wrote:

**Comment by coreh** [comment]
This is now implemented on `master` and will be on the next release.

**Comment by cmundi** [comment]
Nice!!
On Jan 3, 2012 4:48 PM, "Marco Aurlio" <
reply@reply.github.com>
wrote:
