### ISSUE TITLE
Stateful Per-File Cursors?

### ISSUE THREAD

**Issue by cmundi** [coreh-deprecated/nide#35]
Is it feasible for nide to remember the last-known cursor position within a file and return to that position the next time the file is selected/opened?  This would not have to persist across sessions.

**Comment by coreh** [comment]
Hmm, yeah. 

The CodeMirror editing component is currently destroyed whenever you switch between files. Perhaps we could just hide it? 

To keep memory usage on a sane level, if there are more than a set number of components (say 10 or 20) we could just destroy the least recently used one.

**Comment by cmundi** [comment]
That sounds very reasonable.
On Dec 31, 2011 11:44 AM, "Marco Aurlio" <
reply@reply.github.com>
wrote:

**Comment by coreh** [comment]
@cmundi: This is now implemented in master, and will ship with the next version.

**Comment by cmundi** [comment]
Pure genius.  I am really enjoying nide on my current project.
On Jan 3, 2012 7:00 PM, "Marco Aurlio" <
reply@reply.github.com>
wrote:
