### ISSUE TITLE
die when meeting a broken symlink

### ISSUE THREAD

**Issue by dready92** [coreh-deprecated/nide#36]
Hello,

in my project I got a broken symbolic link, and nide totally die on this one with error :

```
/home/mbailly/Documents/perso/d10js/node-0.6.6/lib/node_modules/nide/server/project.js:154
          if (err) throw err
                         ^
Error: ENOENT, no such file or directory '/home/mbailly/tmp/(...)/README'
```

**Comment by coreh** [comment]
Oops, we probably shouldn't throw an error like this. I'll change it so the event is logged to `stderr`, and the program moves on to the next file.

**Comment by coreh** [comment]
This is now fixed in the repository. The fixed code will be on the next release.

**Comment by dready92** [comment]
really nice thanks !
